/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hun.nik.project.acc;

/**
 *
 * @author Laci
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        myACC = new ACC();
        wheelStateInDegrees = currentSpeed = 0;
        nearestObstacleDistance = 50;
    }

    public IACC myACC;
    public boolean ACCState;

    int wheelStateInDegrees;
    int currentSpeed;
    int nearestObstacleDistance;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ButtonACC = new javax.swing.JButton();
        SliderWheel = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        SliderSpeed = new javax.swing.JSlider();
        SliderObstacleDistance = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonACC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ButtonACC.setText("ACC off");
        ButtonACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonACCActionPerformed(evt);
            }
        });

        SliderWheel.setMajorTickSpacing(10);
        SliderWheel.setMaximum(90);
        SliderWheel.setMinimum(-90);
        SliderWheel.setPaintLabels(true);
        SliderWheel.setPaintTicks(true);
        SliderWheel.setValue(0);
        SliderWheel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderWheelStateChanged(evt);
            }
        });

        jLabel1.setText("Wheel steering");

        SliderSpeed.setMajorTickSpacing(10);
        SliderSpeed.setMaximum(200);
        SliderSpeed.setPaintLabels(true);
        SliderSpeed.setPaintTicks(true);
        SliderSpeed.setValue(0);
        SliderSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderSpeedStateChanged(evt);
            }
        });

        SliderObstacleDistance.setMajorTickSpacing(10);
        SliderObstacleDistance.setPaintLabels(true);
        SliderObstacleDistance.setPaintTicks(true);
        SliderObstacleDistance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderObstacleDistanceStateChanged(evt);
            }
        });

        jLabel2.setText("Speed");

        jLabel3.setText("Distance");

        LabelState.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelState.setText("Do nothing!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonACC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelState, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderObstacleDistance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(SliderSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SliderWheel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonACC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SliderObstacleDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderWheel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderSpeedStateChanged
        // TODO add your handling code here:
        currentSpeed = SliderSpeed.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderSpeedStateChanged

    private void SliderObstacleDistanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderObstacleDistanceStateChanged
        // TODO add your handling code here:
        nearestObstacleDistance = SliderObstacleDistance.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderObstacleDistanceStateChanged

    private void SliderWheelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderWheelStateChanged
        // TODO add your handling code here:
        wheelStateInDegrees = SliderWheel.getValue();
        ChangeLabel();
    }//GEN-LAST:event_SliderWheelStateChanged

    private void ButtonACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonACCActionPerformed
        // TODO add your handling code here:
        if (ACCState) {
            ButtonACC.setText("ACC off");

        } else {
            ButtonACC.setText("ACC on");
        }
        ACCState = !ACCState;
        ChangeLabel();
    }//GEN-LAST:event_ButtonACCActionPerformed

    private void ChangeLabel() {
        myACC.PedalState(wheelStateInDegrees, ACCState, currentSpeed, nearestObstacleDistance);
        int temp = myACC.getPedal();
        switch (temp) {
            case 1:
                LabelState.setText("Throttling!!!");
                break;
            case 0:
                LabelState.setText("Do nothing!!!");
                break;
            default:
                LabelState.setText("Breaking!!!");
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonACC;
    private javax.swing.JLabel LabelState;
    private javax.swing.JSlider SliderObstacleDistance;
    private javax.swing.JSlider SliderSpeed;
    private javax.swing.JSlider SliderWheel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
